"""kakao_link_sessions 테이블 추가

Revision ID: 1ca5f9d0d398
Revises: 06686e1f6508
Create Date: 2026-04-18 14:15:59.034681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca5f9d0d398'
down_revision: Union[str, Sequence[str], None] = '06686e1f6508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kakao_link_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('kakao_id', sa.String(length=100), nullable=False),
    sa.Column('kakao_access_token', sa.String(length=500), nullable=False),
    sa.Column('kakao_refresh_token', sa.String(length=500), nullable=True),
    sa.Column('kakao_expires_in', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kakao_link_sessions_expires_at'), 'kakao_link_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_kakao_link_sessions_kakao_id'), 'kakao_link_sessions', ['kakao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kakao_link_sessions_kakao_id'), table_name='kakao_link_sessions')
    op.drop_index(op.f('ix_kakao_link_sessions_expires_at'), table_name='kakao_link_sessions')
    op.drop_table('kakao_link_sessions')
    # ### end Alembic commands ###
