"""review_stages에 inappropriate_review_needed 컬럼 추가

Revision ID: 1d79e90f3ebe
Revises: 82ddbeabc057
Create Date: 2026-04-17 16:43:21.175378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d79e90f3ebe'
down_revision: Union[str, Sequence[str], None] = '82ddbeabc057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 기존 행은 기본값 false로 채우고, 이후 server_default 제거
    op.add_column(
        'review_stages',
        sa.Column('inappropriate_review_needed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('review_stages', 'inappropriate_review_needed', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_stages', 'inappropriate_review_needed')
    # ### end Alembic commands ###
