"""review_stages에 inappropriate_note 컬럼 추가

Revision ID: 2179b4bec65d
Revises: 86929ae4d301
Create Date: 2026-04-17 19:31:16.732246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2179b4bec65d'
down_revision: Union[str, Sequence[str], None] = '86929ae4d301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_stages', sa.Column('inappropriate_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_stages', 'inappropriate_note')
    # ### end Alembic commands ###
