"""notification_logs recipient_id nullable

Revision ID: 26dd5416f6ab
Revises: 4c2b2569fa54
Create Date: 2026-04-16 18:45:22.704629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26dd5416f6ab'
down_revision: Union[str, Sequence[str], None] = '4c2b2569fa54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_logs', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_logs', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
