"""inquiries.submitter_id 컬럼 추가

Revision ID: 32d60d45abef
Revises: 445e10292bd7
Create Date: 2026-04-18 15:28:44.302996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d60d45abef'
down_revision: Union[str, Sequence[str], None] = '445e10292bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inquiries', sa.Column('submitter_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inquiries_submitter_id'), 'inquiries', ['submitter_id'], unique=False)
    op.create_foreign_key(None, 'inquiries', 'users', ['submitter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_index(op.f('ix_inquiries_submitter_id'), table_name='inquiries')
    op.drop_column('inquiries', 'submitter_id')
    # ### end Alembic commands ###
