"""users 카카오 동의 캐시 컬럼 추가

Revision ID: 34755893cd3c
Revises: aabfa375c25e
Create Date: 2026-04-18 17:10:31.018459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34755893cd3c'
down_revision: Union[str, Sequence[str], None] = 'aabfa375c25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kakao_scopes_ok', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('kakao_scopes_checked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kakao_scopes_checked_at')
    op.drop_column('users', 'kakao_scopes_ok')
    # ### end Alembic commands ###
