"""inappropriate_notes 테이블 + buildings 도면작성자 필드 + inappropriate_note 컬럼 제거

Revision ID: 352699499ffa
Revises: 2179b4bec65d
Create Date: 2026-04-17 19:54:37.797410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352699499ffa'
down_revision: Union[str, Sequence[str], None] = '2179b4bec65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inappropriate_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['review_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inappropriate_notes_stage_id'), 'inappropriate_notes', ['stage_id'], unique=False)
    op.add_column('buildings', sa.Column('drawing_creator_firm', sa.String(length=100), nullable=True))
    op.add_column('buildings', sa.Column('drawing_creator_name', sa.String(length=50), nullable=True))
    op.drop_column('review_stages', 'inappropriate_note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_stages', sa.Column('inappropriate_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('buildings', 'drawing_creator_name')
    op.drop_column('buildings', 'drawing_creator_firm')
    op.drop_index(op.f('ix_inappropriate_notes_stage_id'), table_name='inappropriate_notes')
    op.drop_table('inappropriate_notes')
    # ### end Alembic commands ###
