"""users.kakao_id partial unique 인덱스 추가

Revision ID: 445e10292bd7
Revises: 1ca5f9d0d398
Create Date: 2026-04-18 14:20:52.557518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445e10292bd7'
down_revision: Union[str, Sequence[str], None] = '1ca5f9d0d398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_users_kakao_id_not_null', 'users', ['kakao_id'], unique=True, postgresql_where=sa.text('kakao_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_kakao_id_not_null', table_name='users', postgresql_where=sa.text('kakao_id IS NOT NULL'))
    # ### end Alembic commands ###
