"""초기 테이블 생성

Revision ID: 463340852196
Revises: 
Create Date: 2026-04-14 15:32:00.641646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '463340852196'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('TEAM_LEADER', 'CHIEF_SECRETARY', 'SECRETARY', 'REVIEWER', name='userrole'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('kakao_id', sa.String(length=100), nullable=True),
    sa.Column('kakao_access_token', sa.String(length=500), nullable=True),
    sa.Column('kakao_refresh_token', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_no', sa.String(length=10), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mgmt_no', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('building_type', sa.String(length=50), nullable=True),
    sa.Column('sido', sa.String(length=20), nullable=True),
    sa.Column('sigungu', sa.String(length=30), nullable=True),
    sa.Column('beopjeongdong', sa.String(length=50), nullable=True),
    sa.Column('land_type', sa.String(length=20), nullable=True),
    sa.Column('main_lot_no', sa.String(length=10), nullable=True),
    sa.Column('sub_lot_no', sa.String(length=10), nullable=True),
    sa.Column('special_lot_no', sa.String(length=20), nullable=True),
    sa.Column('building_name', sa.String(length=200), nullable=True),
    sa.Column('main_structure', sa.String(length=100), nullable=True),
    sa.Column('other_structure', sa.String(length=200), nullable=True),
    sa.Column('main_usage', sa.String(length=100), nullable=True),
    sa.Column('other_usage', sa.String(length=200), nullable=True),
    sa.Column('gross_area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('floors_above', sa.Integer(), nullable=True),
    sa.Column('floors_below', sa.Integer(), nullable=True),
    sa.Column('is_special_structure', sa.Boolean(), nullable=True),
    sa.Column('is_high_rise', sa.Boolean(), nullable=True),
    sa.Column('is_multi_use', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('architect_firm', sa.String(length=100), nullable=True),
    sa.Column('architect_name', sa.String(length=50), nullable=True),
    sa.Column('struct_eng_firm', sa.String(length=100), nullable=True),
    sa.Column('struct_eng_name', sa.String(length=50), nullable=True),
    sa.Column('high_risk_type', sa.String(length=100), nullable=True),
    sa.Column('related_tech_coop', sa.Boolean(), nullable=True),
    sa.Column('drawing_creation', sa.Boolean(), nullable=True),
    sa.Column('current_phase', sa.String(length=30), nullable=True),
    sa.Column('final_result', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['reviewers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_mgmt_no'), 'buildings', ['mgmt_no'], unique=True)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('related_building_id', sa.Integer(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('PRELIMINARY', 'SUPPLEMENT_1', 'SUPPLEMENT_2', 'SUPPLEMENT_3', 'SUPPLEMENT_4', 'SUPPLEMENT_5', name='phasetype'), nullable=False),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.Column('doc_received_at', sa.Date(), nullable=True),
    sa.Column('doc_distributed_at', sa.Date(), nullable=True),
    sa.Column('report_submitted_at', sa.Date(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=50), nullable=True),
    sa.Column('result', sa.Enum('PASS', 'SUPPLEMENT', 'FAIL', 'MINOR', name='resulttype'), nullable=True),
    sa.Column('review_opinion', sa.Text(), nullable=True),
    sa.Column('defect_type_1', sa.String(length=100), nullable=True),
    sa.Column('defect_type_2', sa.String(length=100), nullable=True),
    sa.Column('defect_type_3', sa.String(length=100), nullable=True),
    sa.Column('objection_filed', sa.Boolean(), nullable=True),
    sa.Column('objection_content', sa.Text(), nullable=True),
    sa.Column('objection_reason', sa.Text(), nullable=True),
    sa.Column('s3_file_key', sa.String(length=500), nullable=True),
    sa.Column('stage_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_stages')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_buildings_mgmt_no'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_table('reviewers')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
