"""inquiries 테이블 추가

Revision ID: 47f787cb8b11
Revises: 26dd5416f6ab
Create Date: 2026-04-17 09:19:05.321140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f787cb8b11'
down_revision: Union[str, Sequence[str], None] = '26dd5416f6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('mgmt_no', sa.String(length=20), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('submitter_name', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ASKING_AGENCY', 'COMPLETED', 'NEXT_PHASE', name='inquirystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiries')
    # ### end Alembic commands ###
