"""Building에 assigned_reviewer_name 필드 추가

Revision ID: 4c2b2569fa54
Revises: 1995f7d916c4
Create Date: 2026-04-16 13:45:35.171466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2b2569fa54'
down_revision: Union[str, Sequence[str], None] = '1995f7d916c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('assigned_reviewer_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'assigned_reviewer_name')
    # ### end Alembic commands ###
