"""add kakao_uuid and token_expires_at to user

Revision ID: 82ddbeabc057
Revises: e563f2c70102
Create Date: 2026-04-17 14:07:19.708686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82ddbeabc057'
down_revision: Union[str, Sequence[str], None] = 'e563f2c70102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kakao_uuid', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('kakao_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kakao_token_expires_at')
    op.drop_column('users', 'kakao_uuid')
    # ### end Alembic commands ###
