"""password_setup_tokens 테이블 추가

Revision ID: aabfa375c25e
Revises: 32d60d45abef
Create Date: 2026-04-18 15:54:00.069231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabfa375c25e'
down_revision: Union[str, Sequence[str], None] = '32d60d45abef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_setup_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('INITIAL_SETUP', 'PASSWORD_RESET', name='tokenpurpose'), nullable=False),
    sa.Column('delivery_channel', sa.Enum('KAKAO', 'MANUAL', name='tokendeliverychannel'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_setup_tokens_expires_at'), 'password_setup_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_setup_tokens_token_hash'), 'password_setup_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_setup_tokens_user_id'), 'password_setup_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_setup_tokens_user_id'), table_name='password_setup_tokens')
    op.drop_index(op.f('ix_password_setup_tokens_token_hash'), table_name='password_setup_tokens')
    op.drop_index(op.f('ix_password_setup_tokens_expires_at'), table_name='password_setup_tokens')
    op.drop_table('password_setup_tokens')
    # ### end Alembic commands ###
