"""buildings에 drawing_creator_qualification 컬럼 추가

Revision ID: e21306ca9ca6
Revises: 352699499ffa
Create Date: 2026-04-17 20:54:07.047263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21306ca9ca6'
down_revision: Union[str, Sequence[str], None] = '352699499ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('drawing_creator_qualification', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'drawing_creator_qualification')
    # ### end Alembic commands ###
