"""buildings에 내진등급 유형별상세검토 필드 추가

Revision ID: e563f2c70102
Revises: 47f787cb8b11
Create Date: 2026-04-17 12:57:11.818840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e563f2c70102'
down_revision: Union[str, Sequence[str], None] = '47f787cb8b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('seismic_level', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category1', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category2', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category3', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category4', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category5', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category6', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category7', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category8', sa.String(length=50), nullable=True))
    op.add_column('buildings', sa.Column('detail_category9', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'detail_category9')
    op.drop_column('buildings', 'detail_category8')
    op.drop_column('buildings', 'detail_category7')
    op.drop_column('buildings', 'detail_category6')
    op.drop_column('buildings', 'detail_category5')
    op.drop_column('buildings', 'detail_category4')
    op.drop_column('buildings', 'detail_category3')
    op.drop_column('buildings', 'detail_category2')
    op.drop_column('buildings', 'detail_category1')
    op.drop_column('buildings', 'seismic_level')
    # ### end Alembic commands ###
